#!/usr/bin/env python

import sys
from pt.proc import ps_kill

try:
    ps_kill.hardKill(sys.argv[1])
except IndexError:
    print "Usage: %s <StartPid> (find StartPid via ps auxf!)" % sys.argv[0]
    sys.exit(1)

