# docker-compose config for xibe stack: web server, php and postgresql
---

version: '3'

services:

  # nginx frontend
  nginx:
    hostname: xibe-nginx
    container_name: xibe-nginx
    image: xibe-nginx:1.0
    build: ./build/nginx
    depends_on:
    - php
    - postgres
    ports:
    - 0.0.0.0:8081:80
    volumes:
    - ./site.conf:/etc/nginx/conf.d/default.conf:rw
    - ./www:/var/www/html:ro
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'Europe/Berlin'
    logging:
      driver: json-file
      options:  # max 100MB
        max-size: '5M'
        max-file: '20'
    restart: unless-stopped

  # php backend
  php:
    hostname: xibe-php
    container_name: xibe-php
    image: xibe-php:7.4
    build: ./build/php7.4
    volumes:
    - ./www:/var/www/html:rw
    environment:
      PUID: 1000
      PGID: 1000
      POSTGRES_HOST: 'postgres'
      POSTGRES_DB: xibe
      POSTGRES_USER: xibe
      POSTGRES_PASSWORD: '2WhhI(ewsnln.^G\@c'
      TZ: 'Europe/Berlin'
    logging:
      driver: json-file
      options:  # max 100MB
        max-size: '5M'
        max-file: '20'
    restart: unless-stopped

  # database backend
  postgres:
    container_name: xibe-postgres
    hostname: xibe-postgres
    image: postgres:11
    volumes:
      - postgres:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: xibe   
      POSTGRES_PASSWORD: '2WhhI(ewsnln.^G\@c'
      TZ: 'Europe/Berlin'
    logging:
      driver: json-file
      options:  # max 100MB
        max-size: '5M'
        max-file: '20'
    restart: unless-stopped

volumes:
  postgres:

# vim:sw=2:ts=2:et:
