#!/usr/bin/env python
# -*- coding: utf-8 -*-
#vim:fdm=marker
# unlock vim folding via zR, zo and lock folding via zM, zc
#----------------------------------------------------------------------------
"""                                                                     
 DESCRIPTION  some shell tools for python scripts                        {{{1
 
 USAGE        call this script with -h or --help option
       
 CHANGELOG    
    09-06-23    * creation, copied from

 TODO
 
 THANKS TO

"""

__version__ = "$Revision: 0.1.2010-01-31 $"
# $Source$

 
#----------------------------------------------------------------------------
# modules import, constants                                              {{{1
#----------------------------------------------------------------------------
# standard

# extra modules
 
# constants, default values
CONFIG_DIR = '/etc/xen'        
 
 
 
#----------------------------------------------------------------------------
# main classes                                                           {{{1
#----------------------------------------------------------------------------

    #------------------------------------------------------------------------
    #                                                                    {{{2   
    #------------------------------------------------------------------------
 
#----------------------------------------------------------------------------
# test structure                                                         {{{1
#----------------------------------------------------------------------------
if __name__ == "__main__":
    import sys
    import os
    import logging

    log = logging.getLogger('fly.test')
    log.addHandler(logging.StreamHandler())
    log.setLevel(logging.DEBUG)

    sys.exit(0)

