#!/bin/sh -eu
# Usage: this-script HOST1 [HOST2] [HOSTn]"
# 
# Shows collected facts for given host(s)"
LANG=C



# contants
REDIS_CONTAINER=ansible-redis
SCRIPT_PATH="$(readlink -e "$0")"


# collect options and parameters
usage() { awk -F '# ' '!NF{exit}{print $2}' "$0"; } # filter script comment
while [ $# -gt 0 ]; do

    case "$1" in
    -h|--help)
        usage
        exit 0
    ;;
    *)
        HOSTS="${HOSTS:-} $1"
        shift 1
    ;;
    esac
done

# validate input

# set up tempdir and auto-removal
TEMP_DIR=$(mktemp -d --suffix="$(basename "$0")")
trap "{ rm -rf $TEMP_DIR; }" EXIT




# host patterns given - do it
if [ ! -z "$HOSTS" ]; then

    docker exec $REDIS_CONTAINER redis-cli mget $HOSTS

# missing host patterns - exit
else

    usage
    exit 1

fi

# GMA 2021
# vim: ts=4:sw=4:ft=sh:et
