#!/usr/bin/env python


import sys
import os

PT_DIR='pt'

pathes = sys.path + ['/home/mint', '/home/gunnar', '/home/gmann', '/root']


# scan system path for 'pt' dir
for directory in pathes:
    # skip empty lines
    if directory == '':
        continue
    try:
        for entry in os.listdir(directory): 
        
            if entry == PT_DIR:
                print  directory + os.sep + entry
    except OSError, emsg:
        if emsg[0] == 'Errno 2':
            pass
