#!/bin/bash

# show size of different tables

LANG=C          # avoid errors due to localized command output
set -o nounset  # avoid using non initialised variables (rm -rf /$dir)
set -o errexit  # exit the script at non-true return value
set -o pipefail # catch errors from all parts of shell pipes

MYSQL_OPTIONS="--defaults-extra-file=/etc/mysql/debian.cnf --default-character-set=utf8"


query_sizes() {
    local $Database="$1"
    mysql $MYSQL_OPTIONS -Bs << QUERY_END
        SELECT table_name AS 'Tables', 
            round(((data_length+index_length)/1024/1024),2) 'Size in MB' 
        FROM information_schema.TABLES 
        WHERE table_schema ="$Database" 
        ORDER BY (data_length + index_length) DESC 
QUERY_END

}


for Database in $( mysql $MYSQL_OPTIONS -NB -e 'show databases'); do 
    query_sizes $Database | while read Line; do
        echo "$Database.$Line"
    done
done
