#!/bin/bash
# defragment all tables in current mysql by running OPTIMIZE_TABLE
LANG=C          # avoid errors due to localized command output
set -o nounset  # avoid using non initialised variables (rm -rf /$dir)
set -o errexit  # exit the script at non-true return value
set -o pipefail # catch errors from all parts of shell pipes

MYSQL_OPTIONS="--defaults-extra-file=/etc/mysql/debian.cnf --default-character-set=utf8" 

# helper function
# return all db table free_space for fragmented tables
# The DATA_FREE column shows the free space in bytes for InnoDB tables
get_fragmented_tables() { 
	mysql $MYSQL_OPTIONS -Bse "
		SELECT table_schema,table_name,data_free,data_length,engine
		FROM information_schema.tables
		WHERE data_free > 0
		ORDER BY data_free
	"
}

print_bytes() {
	local bytes=$1
	echo $(numfmt --to=iec-i --round=nearest $bytes )B
}

# MyISAM - run optimize table
get_fragmented_tables | while read db table free total engine; do
		printf '%-60s' "Optimizing $engine table \"$db.$table\","
		echo -n "free space "
		echo -n "$(print_bytes $free)/$(print_bytes $total) ... "
		mysqlcheck $MYSQL_OPTIONS --optimize $db $table > /dev/null
		echo "ok"
done
