#!/bin/bash
set -euo pipefail

PARENT='/srv'

# get more accurate results
sudo sync

# store all subvolume names
while read x i x g x x l x p
do
    volName[i]=$p
done < <(sudo btrfs subvolume list "$PARENT")

echo -e "subvol\tqgroup\ttotal\tunshared"

while read g r e
do
    group=${g##*/}
    name="${volName[group]:--}"
    echo $name $g $(numfmt --to=iec --round=nearest $r) $(numfmt --to=iec --round=nearest $e)

done < <(sudo btrfs qgroup show --raw "$PARENT" | tail -n+3) | column -t
