#!/bin/bash


BIN="${0%/*}"

Packages="drbd8-utils drbd8-modules python"

#------------------------------------------------------------------------------
# some initial checks and definitions
#------------------------------------------------------------------------------
echo ">>> script setup"

# stop on each error
    set -e

# helper functions
    pass() { [[ -z $@ ]] && echo "ok" || echo "$@ ... ok"; }
    die()  { echo "ERROR $@"; exit 1; }
    die_wait()  { echo -e "ERROR $@ \nignore error or break [CTRL_C] ?"; read ; }

# see if target dir is specified
    TargetDir=$1
    if [[ -z $TargetDir ]]; then

    echo "no target chroot dir specified, specify '/' for 'here'"
    exit 1

    fi

# check target dir
    echo -n " * checking chroot '$TargetDir' ... "
	[[ -d $TargetDir ]] && pass || die "error: does not look like a directory, aborting"


#------------------------------------------------------------------------------
# update/ install packages
#------------------------------------------------------------------------------
echo ">>>packages"


    echo " * fixing dependencies of broken packages"
    chroot "$TargetDir" /usr/bin/aptitude --without-recommends install -y -f || die_wait
 
# install other packages
    echo " * installing other packages"  
    echo "$Packages"
    chroot "$TargetDir" /usr/bin/aptitude --without-recommends install -y $Packages || die_wait


    # clean out installation temp files
    echo -n " * cleaning out downloaded package files ... "
    if [[ $CleanTarget == yes ]]
    then
        chroot "$TargetDir" /usr/bin/aptitude clean > /dev/null && pass || die_wait
    else
        echo "skipping (ok)"
	fi


#------------------------------------------------------------------------------
# install scripts
#------------------------------------------------------------------------------
PYTHON_PATH="$TargetDir/var/lib/python-support/python2.5"


install -vDm 0750 -o 0 -g 0 "$BIN/dr-"*            -t "/bin/"

install -vdm 0555 "$PYTHON_PATH/drbd" 
install -vDm 0644 -o 0 -g 0 "$BIN/__init__.py"  -t "$PYTHON_PATH/drbd/"
install -vDm 0644 -o 0 -g 0 "$BIN/read_config.py"  -t "$PYTHON_PATH/drbd/"

install -vDm 0644 -o 0 -g 0 "$BIN/drbd.conf.example"            -t "/etc/"


